  version: '3'
  services:
    zigbee2mqtt:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: zigbee2mqtt
      image: zigbee2mqtt:1.18.1-dev
      volumes:
        - ./data:/app/data
      restart: always
      network_mode: host
